### ISSUE TITLE
Forfeit vote

### ISSUE THREAD

**Issue by marco93f** [w3champions/w3champions-issues#15]
You can now vote -ff in 4v4 RT with a 3 min CD
If -ff vote completes on team game ends and voting team gets loss other team gets win
If -ff vote completes you are immune to being reported for leaving
If you leave without using -ff vote it's at your own risk

https://discordapp.com/channels/688377338576109643/765623167808831539/768450988691685377

**Comment by marco93f** [comment]
also: take into account prior leavers. every leaver should increase his team's ff counter of +1.

**Comment by alocate** [comment]
this is still a feature that would be valuable and i think across game modes too, for people with code+mapmaking experience for example @marcoabreu

**Comment by alocate** [comment]
(also, marco, meet marco, do all marcos have an interest in mapmaking?)

**Comment by zygissss** [comment]
done

**Comment by BogdanW3** [comment]
This is now implemented for season 12 maps (map-updater-scripts pull request 11) as the -gg command, so I'll close this issue.
