### ISSUE TITLE
Try switching from Glicko2 to TrueSkill

### ISSUE THREAD

**Issue by Qeenon** [w3champions/w3champions-issues#18]
related to https://github.com/w3champions/w3champions-issues/issues/1
(first issue should be closed tho as far as I understand since it's using geomean already there)

https://www.microsoft.com/en-us/research/project/trueskill-ranking-system/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fprojects%2Ftrueskill

> Glicko was developed as an extension of ELO and was thus naturally limited to two player matches which end in either win or loss. Glicko cannot update skill levels of players if they compete in multi-player events or even in teams. The logistic model would make it computationally expensive to deal with team and multi-player games. Moreover, chess is usually played in pre-set tournaments and thus matching the right opponents was not considered a relevant problem in Glicko. In contrast, the TrueSkill ranking system offers a way to measure the quality of a match between any set of players.

 - code: https://github.com/sublee/trueskill
 - old C# realization maybe could be useful too: https://github.com/moserware/Skills

**Comment by Qeenon** [comment]
assign @alocate

**Comment by Cepheid-UK** [comment]
It's glicko2, and it's actually been customised for wc3 to the point where we could call it a different system. We wont be switching to Trueskill sorry.
