### ISSUE TITLE
Launcher is Kind of Hard to Run on Linux

### ISSUE THREAD

**Issue by KoryMac** [w3champions/w3champions-issues#23]
Manual install into a warcraft 3 wine prefix works fine
Getting the launcher to work is quite a bit trickier; I haven't been able to use it yet
Because of this Flo is unavailable to me
Not sure what would be required to port the w3c launcher to Linux, or how it would interact with Warcraft III running through WINE
Choosing to not support a platform that is also not supported by the game for which this service was made is reasonable. It would be cool to have Flo on Linux though

**Comment by KoryMac** [comment]
Okay somebody from the w3c discord helped me get it working. It was a little fiddly to get it to work, but I can play on Flo now which is awesome

**Comment by modmoto** [comment]
I will close this as linux is not officially supported. We have the possibility to target it for linux, though and I allready made a few builds with it. If you want to support linux and do know a little bit about programming, we could make this an official verison.

**Comment by Qeenon** [comment]
@KoryMac hello, real problem of flo on linux was discussed here https://github.com/stbuehler/rust-async-dnssd/issues/16#issue-790818153
I've stopped working on this issue since w3c team is banned me on discord and I've lost motivation there
you can contact me for details if you have interest

**Comment by KoryMac** [comment]
> I will close this as linux is not officially supported. We have the possibility to target it for linux, though and I allready made a few builds with it. If you want to support linux and do know a little bit about programming, we could make this an official verison.

I'd love to do so, but I don't have the skills to. I'm barely getting started with programming. If I ever learn enough to be able to, I will  = ).

**Comment by KoryMac** [comment]
@Qeenon , how is the dnssd issue related? Is that something that came up while you were trying to port the launcher? I've been able to use flo in WINE, and aside from being a bit convoluted to get set up it works pretty well. I don't know if this is actually as much of an issue as it seems like it might be, but because the base game must be ran in WINE at this point, how would you get the w3c client to interact with it if you were to port the w3c client to Linux?

**Comment by modmoto** [comment]
Just for further reference, the launcher and flo can be built for linux, but that will not help that much as WC3 has to be run on wine. So far no one tested if a native launcher and flo would be able to connect with the wine wc3. I guess there are some changes or adjustments needed to make this official. As no one of us has the time or setup for that, we tabled it. If someone wants to takle this, I am happy to help with the linux build for flo an the launcher =)
