### ISSUE TITLE
list of ports required to play

### ISSUE THREAD

**Issue by piercefoospacenug** [w3champions/w3champions-issues#25]
Hi there,

appreciate your work! sorry if this isn't really an issue with any of the software

is there a complete list of tcp/udp ports that required to play on w3champions? Im routing all traffic through a VPN and would like to set up some rules to bypass VPN for w3champions.

thanks

**Comment by abeninski** [comment]
Hey,

Why do you need to route trough vpn? Our server selection doesn't need VPN

**Comment by piercefoospacenug** [comment]
i don't want to play through VPN

I just prefer to use a VPN, as i live in a country that is notorious for collecting everyone's data, therefor i usually configure my router to not use VPN for games... this works fine for wow and csgo for example.

just figured i'd ask if somebody here has a complete list before looking at the network traffic myself
